felt/tippecanoe

CHANGELOG.md, geometry.cpp, geometry.hpp, main.cpp, tile.cpp, version.hpp
Previously there were some cases where dropping the smallest polygons would never reduce the number of labels.
=> Generate label points after simplification, not before.

flatbuffers/base.h, flatbuffers/buffer.h, flatbuffers/flatbuffer_builder.h, flatbuffers/flatbuffers.h, flatbuffers/stl_emulation.h, flatbuffers/table.h, flatbuffers/util.h, flatbuffers/vector.h, flatbuffers/vector_downward.h, flatbuffers/verifier.h, flatgeobuf/feature_generated.h, flatgeobuf/header_generated.h
How:
- Copied files in from the latest release of flatbuffers (v22.9.29) 
- Created `feature_generated.h` & `header_generated.h` using the `src/fbs` files from the latest release of flatgeobuf (3.23.1)
Why:
- The existing files blocked compilation within Alpine Linux
Links:
- https://github.com/felt/tippecanoe/issues/24
- https://github.com/google/flatbuffers/releases/tag/v22.9.29
- https://github.com/flatgeobuf/flatgeobuf/releases/tag/3.23.1
=> Update flatbuffers to v22.9.29

mbtiles.cpp
to match the table definition 
`CREATE TABLE map (zoom_level INTEGER, tile_column INTEGER, tile_row INTEGER, tile_id TEXT);`
and `CREATE TABLE images (tile_data blob, tile_id text);`
* previous blob type worked for internal join, but made querying by text impossible without casting.
=> Change mbtiles tile_id inserts from blob to text

mbtiles.cpp
This is the simplest standard hash function for this use case. I verified the output is the same as go's `hash/fnv` 64-bit output.
=> change hash function to fnv1a

Makefile, README.md, tests/readfile/readfile.list, tile-join.cpp
In response to #69 add a -r to allow passing a file containing the list of files to use as source inputs to join
=> Allow passing a file with a list of input files to tile-join in response to issue 69

pmtiles/pmtiles.hpp
* remove unused code [#93]
* fix OOB caused by specific entry set lengths
* add more checks for valid tile IDs
This resolves an off-by-one problem caused by specific entry set lengths and could result in garbage entries being created if that condition is reached, described here in Go: https://github.com/protomaps/go-pmtiles/issues/49
=> update pmtiles.hpp from upstream

projection.cpp
This fixes the compiler errors "'fpclassify' was not declared in this scope":
```
projection.cpp: In function 'void lonlat2tile(double, double, int, long long int*, long long int*)':
projection.cpp:25:32: error: 'fpclassify' was not declared in this scope
int lat_class = fpclassify(lat);
^
projection.cpp:25:32: note: suggested alternative:
In file included from projection.cpp:5:0:
/usr/include/c++/5/cmath:581:5: note:   'std::fpclassify'
fpclassify(_Tp __x)
^
projection.cpp: In function 'void epsg3857totile(double, double, int, long long int*, long long int*)':
projection.cpp:77:30: error: 'fpclassify' was not declared in this scope
int iy_class = fpclassify(iy);
^
projection.cpp:77:30: note: suggested alternative:
In file included from projection.cpp:5:0:
/usr/include/c++/5/cmath:581:5: …
```
=> Change fpclassify() to std::fpclassify()

Makefile
The C++ standard didn't match the utilization inside the code and would fail to compile using the original makefile
=> Update makefile to use c++17 standard

CHANGELOG.md, README.md, man/tippecanoe.1, tile-join.cpp, version.hpp
Like `-y` in `tippecanoe`, this causes only the named attributes to be preserved into the output tiles.
=> Add --include/-y to tile-join

Makefile, flatgeobuf.cpp
- Added -fPIE as g++ 9.4.0 complained and would not link
- Prevent crash by checking for properties before dereferencing.
=> Check for nullptr in call to properties, fixes segfault.

tile-join.cpp
Original issue: https://github.com/mapbox/tippecanoe/issues/817
Adding a try/catch block to catch exceptions when decoding so that an error message is printed detailing which tile caused the exception
=> Try catch exception

.github/CODEOWNERS
I am not immediately qualified to be a reviewer on this repo right now. I am still watching updates on Slack.
=> Remove Can from the codeowners

flatgeobuf.cpp
currently when the # of features is large it segfaults [#125]
There's no good way to test this using a sample file without it being really large, ideas?
=> Fix narrowing of index_size

README.md
Updated the installation instructions to include the Homebrew formula.
Resolves #70 
The Homebrew formula for `tippecanoe` was switched from `mapbox/tippecanoe` over to this project on 2022-Oct-17 with Homebrew/homebrew-core@e02b07c30a47f04068536b3af70106c4b11ca14a thanks to @e-n-f .
=> Updated installation instructions to include Homebrew

README.md
Add internal link to help understand how the layer name will be derived (and how to overwrite the default behavior)
=> Docs: Link to layer name section

CHANGELOG.md, mbtiles.cpp, mbtiles.hpp, tile.cpp, version.hpp
The polygon joint data structure previously used 24 bytes per vertex to store the three relevant points directly. Now it uses 16 bytes per vertex to store the central point plus two hashes for the other two coordinates.
=> Reduce memory use of polygon shard detection

Makefile
When running `make test` in a pristine working copy, the `test` target calls the `raw-tiles-test` target, which tries to execute `./tile-join`. But that binary has not been built, yet, at this point. The target fails with an error.
Add the required binaries as dependencies to the test targets in the `Makefile`. This makes sure that they are built before they are attempted to be executed.
=> Fix "make test": build required binaries first

CHANGELOG.md, tile-join.cpp, version.hpp
This makes a surprisingly large improvement to speed.
Before:
```
(.venv) Erica-Felt% ./tippecanoe --version                                                                            
tippecanoe v2.34.0
(.venv) Erica-Felt% time ./tile-join --overzoom -z16 -f -o foo.mbtiles  50707ddf-fd34-5d1f-a855-7eedba0b8e00/pmtiles/*
./tile-join --overzoom -z16 -f -o foo.mbtiles   82.53s user 4.60s system 70% cpu 2:04.14 total
```
After:
```
(.venv) Erica-Felt% ./tippecanoe --version                                                                            
tippecanoe v2.34.1
(.venv) Erica-Felt% time ./tile-join --overzoom -z16 -f -o foo.mbtiles  50707ddf-fd34-5d1f-a855-7eedba0b8e00/pmtiles/*
./tile-join --overzoom -z16 -f -o foo.mbtiles   0.90s user 0.23s system 99% cpu 1.146 total
```
(`50707ddf` …
=> Pull from the back of the list of tiles to overzoom, not the front

CHANGELOG.md, clip.cpp, geometry.hpp, overzoom.cpp, tile-join.cpp, version.hpp
When generating an overzoomed tile, check what child tiles it will have at the next zoom level, and queue only those tiles to be overzoomed at the next zoom level.
=> Reduce tile-join overzooming memory usage

CHANGELOG.md, tile.cpp, version.hpp
* When coalescing-as-needed, immediately drop complete geometries that are identical, since the duplicates will be collapsed later on in cleaning anyway
* When simplifying and cleaning geometries early to reduce the total memory footprint for geometry, concatenate multiple geometries together instead of preserving the individual identity of coalesced features
* When converting between feature representations within each tile (from `partial` to `coalesce` to `mvt_feature`), clear out the old representations while building the new instead of waiting to clear the old until they have all been converted
=> Reduce memory consumption during tiling

main.cpp, mbtiles.cpp, mbtiles.hpp, plugin.cpp, serial.cpp, serial.hpp, tile-join.cpp, tile.cpp
Renames internal types and variables related to tilestats:
* `type_and_string` is merged into `serial_val`
* `type_and_string_stats` becomes `tilestat` (singular, for a single attribute)
* `file_keys` becomes `tilestats`
=> Clean up internal naming related to tilestats

CHANGELOG.md, Makefile, README.md, attribute.cpp, attribute.hpp, clip.cpp, geometry.hpp, main.cpp, man/tippecanoe.1, overzoom.cpp, tests/ne_110m_populated_places/out/-z0_-r2_-B3_-yNAME_--retain-points-multiplier_3_--order-by_NAME.json, tests/ne_110m_populated_places/out/-z0_-r2_-B3_-yNAME_--retain-points-multiplier_3_--preserve-input-order.json, tests/pbf/0-0-0-pop-accum.pbf.json, tile-join.cpp, tile.cpp, tile.hpp, version.hpp
This allows, for instance, cluster size summation for heatmaps to work when overzooming tiles that were generated with a retain points multiplier.
In addition, when tiles are generated with a multiplier and a feature order, the multiplier clusters are still sorted into that order, but the features within the cluster remain in spatial sequence instead, so that the default feature for each multiplier cluster remains the same feature that would have been included in the tile if there were no multiplier.
=> Add --accumulate-attribute to tippecanoe-overzoom

.github/workflows/test.yml
This adds a 2nd test run on CI to compile and test the project in debug mode (un-optimized binaries). In my experience sometimes C/C++ bugs can manifest more clearly in debug mode (or even break tests in debug mode while they still pass in release mode). The usefulness of this therefore, that this additional testing may help catch bugs on CI in the future.
The CI runs will take longer. If this slowness presents a problem, or undesirable wait, we could change the `Makefile` to build debug binaries with `-O1` instead of the default of `-O1` so the tests run slightly faster.
=> [ci] test in debug mode

README.md
I believe there is a typo in the current table of precision values. The README says a few lines after the table:
> All internal math is done in terms of a 32-bit tile coordinate system, so 1/(2^32) of the size of Earth, or about 1cm, is the smallest distinguishable distance. If maxzoom + detail > 32, no additional resolution is obtained than by using a smaller maxzoom or detail, and the detail of tiles will be reduced to the maximum that can be used with the specified maxzoom.
So there shouldn't be a zoom level where the precision is better than 1 cm.
=> highz precision values

.github/workflows/test.yml, CHANGELOG.md, Makefile, clip.cpp, dirtiles.cpp, geometry.cpp, main.cpp, mvt.cpp, pmtiles_file.cpp, serial.cpp, shared_borders.cpp, tile-join.cpp, tile.cpp, version.hpp
Previously, the `--preserve-feature-order` sort in `tippecanoe-overzoom` could accidentally get the features out of order by using an unstable sort where all rows have the same sort key. Now it uses `std::stable_sort` to ensure order stability.
The change to the Makefile is to remove the Debug test that was added in https://github.com/felt/tippecanoe/pull/202 and will be fixed in https://github.com/felt/tippecanoe/pull/209.
=> Stabilize feature order in overzoom

CHANGELOG.md, tests/loop/out/-z0_-O200_--cluster-densest-as-needed.json, tests/loop/out/-z0_-O200_--drop-densest-as-needed.json, tests/loop/out/-z0_-O200_--drop-fraction-as-needed.json, tests/muni/out/-Z11_-z13_-O100_--cluster-densest-as-needed.json, tile.cpp, version.hpp
This PR makes two changes to Tippecanoe to reduce memory consumption:
1. As features are converted to `mvt_feature` to add them to the output tile, erase their `serial_feature` representation
2. When the number of features scheduled to be included in the tile reaches the maximum feature count, don't wait any longer to start finding features to drop
=> Reduce tiling memory

flatgeobuf.cpp
The if statement for MultiLineString in `readGeometry` uses `h_geometry_type` instead of the updated `geometry_type`. This causes error when reading a MultiLineString.
=> Fix a bug when reading MultiLineString from .fgb file

Dockerfile, README.md
Micro-optimizations for the Docker images. In the builder image we don't need all of build-essential, that is for package maintainers. We also don't need to install -dev packages in the final image, because we don't need headers and docs. Net result is slightly snappier build the first time, and a 25% reduction in final image size.
=> Minor dockerfile optimizations

CHANGELOG.md, Makefile, clip.cpp, version.hpp
There was a special case to avoid spending time clipping the geometries when the output zxy was the same as the input zxy, but it also prevented clipping in the cases where I *wanted* clipping to happen and was calling tippecanoe-overzoom specifically to do it.
=> Remove buggy optimization to avoid reclipping in overzoom

CHANGELOG.md, decode.cpp, version.hpp
Tippecanoe-decode had a 50 MB limit on the size of single tiles to decode, I think to keep it from risking trying to read an entire mbtiles file into memory to try to decode it as a tile. But I am now running into a tile larger than 50 MB that I need to decode. So this PR raises the limit to 250 MB and gives a clearer message if that limit is ever exceeded.
=> Raise tippecanoe-decode tile size limit to 250 MB

.github/workflows/test.yml
Same as the Linux CI jobs, but macOS -- something to help make sure that changes are actually portable and don't break builds or tests on macOS.
The macOS release build configuration is pretty fast (in my initial run, it finished a minute before the Ubuntu release build), though the debug build on macOS was quite a bit slower (~2 minutes longer than the Ubuntu debug build).
If desired, the workflow triggers could be changed to only run the jobs for PRs and commits to main to keep the number of jobs on each commit to a minimum.
=> Add macOS CI jobs

Makefile, main.cpp, platform.cpp, platform.hpp, tile-join.cpp
This moves some of the code that is platform dependent (e.g. getting various bits of system info) into a separate file that can be reused as needed between the different tippecanoe binaries, and should help keep conditional compilation #ifdef's for different operating systems in one place. This is laying the groundwork that will make support for new platforms (such as #293) cleaner/easier to maintain.
=> Consolidate code for getting platform details into one place

.github/workflows/test.yml
GitHub has made arm64 hosted-runners available free to public/open source repositories: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Here are the results from running the CI tests with the change to the build matrix: https://github.com/nightlark/tippecanoe/actions/runs/12837461438
Unfortunately they haven't added anything like a `ubuntu-latest-arm` label, but there have been a number of people commenting on their various announcement posts asking for one... so we'll see if they change their stance.
=> Add native AArch64 Linux CI test jobs

CHANGELOG.md, mvt.cpp, serial.hpp, tile.cpp, version.hpp
This PR makes two further improvements to memory consumption:
1. When sorting the attribute values that are going into the `mvt_layer` to ensure their uniqueness, sort pointers to strings instead of the strings themselves. Clear the values from the vector as they are added to the PBF representation of the tile.
2. Remove the `need_tilestats` set of string attribute keys, since all attribute values that are added or changed in memory in the course of tile creation need to be reflected in tilestats anyway.
=> Reduce memory consumption during tiling and tile encoding

main.cpp, options.hpp, tile.cpp
It could be annoying when you zoom in and some features disappears. I've added a new option, when it's enabled  clusters will be represented by point with  real coordinates, not a mean of all points inside.
=> Option to not averaging clusters of points

README.md
This fixes a very minor style issue in the note about how `--gamma` works.
=> docs: fix typo in readme re: gamma

CHANGELOG.md, attribute.cpp, tests/mean-accumulation/in.json, tests/mean-accumulation/out/-z1_--accumulate-attribute_value%3amean.json, tests/ne_110m_populated_places_nulls/out/-z1_--accumulate-attribute_POP2000%3amean_-yNAME_-yPOP2000.json, tile.cpp, version.hpp
In review of https://github.com/felt/tippecanoe/pull/263, Chris and I had concluded that the accumulating-onto-nothing case would only be used by `--accumulate-numeric-attributes`, which doesn't accumulate the mean, and that I therefore should consider it an internal "can't happen" error if the accumulation code is called to take the mean of a single value.
However, as reported in https://github.com/felt/tippecanoe/issues/328, this code actually does get legitimately called when `--accumulate-attribute` is specified to accumulate the mean of an attribute that is present in some features but not others, when a feature that has the attribute is being accumulated onto one that does not have it. So now the mean of a single value being accumulated onto nothing is that value, and a new test …
=> Add missing case for accumulating the mean of attributes that are inconsistently present

CHANGELOG.md, Makefile, clip.cpp, geometry.hpp, overzoom.cpp, tests/pbf/1.json, tests/pbf/2.json, tests/pbf/merged-dedup.pbf.json, tests/pbf/merged-nodedup.pbf.json, tile-join.cpp, version.hpp
If this option is specified, only the first feature with each unique ID will be included in the overzoomed tile.
=> Add --deduplicate-by-id option to tippecanoe-overzoom

MADE_WITH.md
This updates the broken links in the [MADE_WITH.md](https://github.com/felt/tippecanoe/blob/main/MADE_WITH.md) file to point to Internet Archive versions of the original content.
=> fix broken links in MADE_WITH.md

lambda/README.md
This updates lambda/README.md to reference tippecanoe.py instead of the non-existent lambda_function.py. This prevents confusion for users following the Lambda setup instructions.
=> Fix incorrect file reference in lambda README
